# Generated by Django 4.2.21 on 2025-06-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_cliente_alter_solicitud_codigo_solicitud_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
