# Generated by Django 4.2.21 on 2025-06-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_remove_solicitud_cliente_alter_cliente_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.cliente'),
        ),
    ]
